### ISSUE TITLE
validation error for GPT4All

### ISSUE THREAD

**Issue by joebordes** [vashAI/GPT4All_OwnDocuments_Offline#1]
I am reading and trying your article but get this error when running the code

```
│   130 │   gpt4all_path = './models/gpt4all-converted.bin'                                        │
│   131 │   # Calback manager for handling the calls with  the model                               │
│   132 │   callback_manager = CallbackManager([StreamingStdOutCallbackHandler()])                 │
│ ❱ 133 │   llm = GPT4All(model=gpt4all_path, callback_manager=callback_manager, verbose=True)     │
│   134 │   best_matching_entry = find_best_matching_prompt(question, KBIndex) 
```
ValidationError: 1 validation error for GPT4All
__root__
  __init__() takes exactly 1 positional argument (2 given) (type=type_error)

maybe due to some deprecation or langchain version?  can you help indicating what may be wrong?

thanks

**Comment by vashAI** [comment]
Hey,

I will check it right away tomorrow morning, which versions of the package
I have installed and then I revert back to you.

**Comment by vashAI** [comment]
I use this version of langchain
langchain.__version__ --> '0.0.149'

**Comment by joebordes** [comment]
Do you have some time to see if it works with the latest version? I'm using 0.0.195

**Comment by vashAI** [comment]
I used the latest version now for your solution: 0.0.197

from bs4 import BeautifulSoup
import requests
import json

from sentence_transformers import SentenceTransformer
import faiss

from langchain import PromptTemplate, LLMChain
#from langchain.callbacks import CallbackManager
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
from langchain.llms import GPT4All

# Callbacks support token-wise streaming
callbacks = [StreamingStdOutCallbackHandler()]
# Verbose is required to pass to the callback manager
llm = GPT4All(model='./models/ggml-gpt4all-l13b-snoozy.bin', callbacks=callbacks, verbose=True)

**Comment by joebordes** [comment]
Yes, that worked. Thanks :-)
